### ISSUE TITLE
Some bug occurred after warming up

### ISSUE THREAD

**Issue by RIvance** [RangiLyu/nanodet#116]
pytorch = 1.7.1
cudnn = 7.6.3
cuda = 10.1

Everything(include the warming up process) goes right before starting training

```
[root][01-13 19:06:43]INFO:distributed sampler set epoch at 1
Traceback (most recent call last):
  File "tools/train.py", line 92, in <module>
    main(args)
  File "tools/train.py", line 87, in main
    trainer.run(train_dataloader, val_dataloader, evaluator)
  File "/home/xxx/Workspace/nanodet-main/nanodet/trainer/trainer.py", line 136, in run
    results, train_loss_dict = self.run_epoch(epoch, train_loader, mode='train')
  File "/home/xxx/Workspace/nanodet-main/nanodet/trainer/trainer.py", line 74, in run_epoch
    data_loader.sampler.set_epoch(epoch)
AttributeError: 'RandomSampler' object has no attribute 'set_epoch'
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/nanodet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xxx/anaconda3/envs/nanodet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xxx/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/xxx/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/xxx/anaconda3/envs/nanodet/bin/python', '-u', 'tools/train.py', '--local_rank=0', 'config/nanodet_roco.yml']' returned non-zero exit status 1.
```

**Comment by RangiLyu** [comment]
What is the command you use to start training? It seems that you started distributed training but didn't use distributed dataloader. Please follow the training guide in readme and run the right training command for single GPU or multi GPU.

**Comment by StephanPan** [comment]
i met the same problem, the reason is that the training command is not corresponding to the config file (gpu_ids).
