### ISSUE TITLE
训练时出错

### ISSUE THREAD

**Issue by job2003** [RangiLyu/nanodet#125]
使用VOC数据进行模型训练，出现以下错误：
 PS D:\workspace\nanodet>  python.exe .\tools\train.py .\config\nanodet_VOC.yml
[root][01-23 08:19:11]INFO:Using Tensorboard, logs will be saved in workspace/nanodet_voc\logs
[root][01-23 08:19:11]INFO:Creating model...
model size is  1.0x
init weights...
Downloading: "https://download.pytorch.org/models/shufflenetv2_x1-5666bf0f80.pth" to C:\Users\whu_c/.cache\torch\hub\checkpoints\shufflenetv2_x1-5666bf0f80.pth
100%|██████████████████████████████████████████████████████████████████████████████| 8.79M/8.79M [00:26<00:00, 347kB/s]
=> loading pretrained model https://download.pytorch.org/models/shufflenetv2_x1-5666bf0f80.pth
Finish initialize Lite GFL Head.
[root][01-23 08:19:39]INFO:Setting up data...
[root][01-23 08:19:39]INFO:loading annotations into memory...
[root][01-23 08:19:39]INFO:Found 22136 annotation files.
Traceback (most recent call last):
  File ".\tools\train.py", line 92, in <module>
    main(args)
  File ".\tools\train.py", line 56, in main
    train_dataset = build_dataset(cfg.data.train, 'train')
  File "d:\workspace\nanodet\nanodet\data\dataset\__init__.py", line 12, in build_dataset
    return XMLDataset(mode=mode, **dataset_cfg)
  File "d:\workspace\nanodet\nanodet\data\dataset\xml_dataset.py", line 44, in __init__
    super(XMLDataset, self).__init__(**kwargs)
  File "d:\workspace\nanodet\nanodet\data\dataset\base.py", line 52, in __init__
    self.data_info = self.get_data_info(ann_path)
  File "d:\workspace\nanodet\nanodet\data\dataset\xml_dataset.py", line 123, in get_data_info
    coco_dict = self.xml_to_coco(ann_path)
  File "d:\workspace\nanodet\nanodet\data\dataset\xml_dataset.py", line 84, in xml_to_coco
    ymin = int(_object.find('bndbox').find('ymin').text)
ValueError: invalid literal for int() with base 10: '45.70000076293945'

训练使用了VOC数据。

**Comment by job2003** [comment]
把ymin = int(_object.find('bndbox').find('ymin').text)
修改为ymin = float(_object.find('bndbox').find('ymin').text)问题解决。
