### ISSUE TITLE
Error running test.py

### ISSUE THREAD

**Issue by TD-wzw** [RangiLyu/nanodet#132]
Loading and preparing results...
Traceback (most recent call last):
  File "tools/test.py", line 65, in <module>
    main(args)
  File "tools/test.py", line 55, in main
    eval_results = evaluator.evaluate(results, cfg.save_dir, 0, logger, rank=local_rank)
  File "/disk_2t_02/wangzhiwei/nanodet/nanodet/evaluator/coco_detection.py", line 55, in evaluate
    coco_dets = self.coco_api.loadRes(json_path)
  File "/home/lhw/anaconda3/envs/pytorch1.6/lib/python3.8/site-packages/pycocotools/coco.py", line 328, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range

**Comment by RangiLyu** [comment]
test.py running the same code with the validation during training. Maybe the same issue in #120 .
