### ISSUE TITLE
RepVGG demo

### ISSUE THREAD

**Issue by chingi071** [RangiLyu/nanodet#143]
您好，我訓練完 RepVGG 做demo時，會出現以下問題，想請問一下應該怎麼解決呢?
另外，他有支援 ncnn demo 嗎? 我轉換成 .bin .param 後執行會有錯誤，謝謝您。

```
python demo/demo.py webcam --config self_train/nanodet-RepVGG-A0_416.yml --model self_train/model_best_vgg.pth --camid 0
Traceback (most recent call last):
  File "demo/demo.py", line 106, in <module>
    main()
  File "demo/demo.py", line 80, in main
    predictor = Predictor(cfg, args.model, logger, device='cuda:0')
  File "demo/demo.py", line 30, in __init__
    model = build_model(cfg.model)
  File "c:\users\joyle\desktop\chingi\nanodet\nanodet\model\arch\__init__.py", line 6, in build_model
    model = GFL(model_cfg.arch.backbone, model_cfg.arch.fpn, model_cfg.arch.head)
  File "c:\users\joyle\desktop\chingi\nanodet\nanodet\model\arch\gfl.py", line 9, in __init__
    super(GFL, self).__init__(backbone_cfg,
  File "c:\users\joyle\desktop\chingi\nanodet\nanodet\model\arch\one_stage.py", line 15, in __init__
    self.backbone = build_backbone(backbone_cfg)
  File "c:\users\joyle\desktop\chingi\nanodet\nanodet\model\backbone\__init__.py", line 20, in build_backbone
    raise NotImplementedError
NotImplementedError
```

**Comment by RangiLyu** [comment]
重新运行setup.py配置一下nanodet环境试试

**Comment by RangiLyu** [comment]
转ncnn后nanodet.h里的heads_info对应的输出blob name要与新的param文件对应

**Comment by chingi071** [comment]
您好，已經成功了! 非常感謝您 !
