### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by wwdok** [RangiLyu/nanodet#146]
I am training the model, when it first time comes to evaluation, it happened following error : 
```
[root][02-07 20:09:23]INFO:val|Epoch10/190|Iter851(0/76)| lr:1.40e-01| loss_qfl:0.2004| loss_bbox:0.4393| loss_dfl:0.2042|
[root][02-07 20:09:24]INFO:val|Epoch10/190|Iter851(10/76)| lr:1.40e-01| loss_qfl:0.3160| loss_bbox:0.3100| loss_dfl:0.2073|
[root][02-07 20:09:24]INFO:val|Epoch10/190|Iter851(20/76)| lr:1.40e-01| loss_qfl:0.3215| loss_bbox:0.3318| loss_dfl:0.2121|
[root][02-07 20:09:25]INFO:val|Epoch10/190|Iter851(30/76)| lr:1.40e-01| loss_qfl:0.2737| loss_bbox:0.2920| loss_dfl:0.2102|
[root][02-07 20:09:25]INFO:val|Epoch10/190|Iter851(40/76)| lr:1.40e-01| loss_qfl:0.2582| loss_bbox:0.3592| loss_dfl:0.2297|
[root][02-07 20:09:25]INFO:val|Epoch10/190|Iter851(50/76)| lr:1.40e-01| loss_qfl:0.3807| loss_bbox:0.3437| loss_dfl:0.2122|
[root][02-07 20:09:26]INFO:val|Epoch10/190|Iter851(60/76)| lr:1.40e-01| loss_qfl:0.1394| loss_bbox:0.2541| loss_dfl:0.1837|
[root][02-07 20:09:26]INFO:val|Epoch10/190|Iter851(70/76)| lr:1.40e-01| loss_qfl:0.1830| loss_bbox:0.3593| loss_dfl:0.1989|
Loading and preparing results...
DONE (t=0.02s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train.py", line 92, in <module>
    main(args)
  File "tools/train.py", line 87, in main
    trainer.run(train_dataloader, val_dataloader, evaluator)
  File "C:\MachineLearning\CV\Object_Detection\nanodet\nanodet\trainer\trainer.py", line 148, in run
    eval_results = evaluator.evaluate(results, self.cfg.save_dir, epoch, self.logger, rank=self.rank)
  File "C:\MachineLearning\CV\Object_Detection\nanodet\nanodet\evaluator\coco_detection.py", line 56, in evaluate
    coco_eval = COCOeval(copy.deepcopy(self.coco_api), copy.deepcopy(coco_dets), "bbox")
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycocotools\cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycocotools\cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycocotools\cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\function_base.py", line 113, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```
My numpy version is 1.19.4.
What might be the cause ? Thanks !

**Comment by wwdok** [comment]
Fine, when i downgrade numpy to 1.17, it works.
