### ISSUE TITLE
config yaml里写中文注释就会报错

### ISSUE THREAD

**Issue by wwdok** [RangiLyu/nanodet#184]
训练时报错如下：
```
E:\Repo\nanodet (main -> origin)
λ python tools/train.py E:\Repo\nanodet\config\nanodet_custom_xml_dataset_special_vehicle.yml
Traceback (most recent call last):
  File "tools/train.py", line 92, in <module>
    main(args)
  File "tools/train.py", line 42, in main
    load_config(cfg, args.config)
  File "e:\repo\nanodet\nanodet\util\config.py", line 31, in load_config
    cfg.merge_from_file(args_cfg)
  File "e:\repo\nanodet\nanodet\util\yacs.py", line 212, in merge_from_file
    cfg = self.load_cfg(f)
  File "e:\repo\nanodet\nanodet\util\yacs.py", line 349, in load_cfg
    return cls._load_cfg_from_file(cfg_file_obj_or_str)
  File "e:\repo\nanodet\nanodet\util\yacs.py", line 358, in _load_cfg_from_file
    return cls._load_cfg_from_yaml_str(file_obj.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 2509: illegal multibyte sequence
```

**Comment by RangiLyu** [comment]
已修复
