### ISSUE TITLE
Train process lock

### ISSUE THREAD

**Issue by Zhiyuan-Li-ANU** [RangiLyu/nanodet#194]
Probelm description:
Using individual data to train nandel-m model. The dataset is from GTSRB. Train samples  number is 461 with 767 boxes. Validation samples number is 45 with 71 boxes. After start warming up step, process has been locked.
Information Copy:
creating index...
index created!
[root][03-26 19:49:18]INFO:Training batch size: 16
[root][03-26 19:49:19]INFO:Starting training...
[root][03-26 19:49:19]INFO:Start warming up...
^CTraceback (most recent call last):
  File "tools/train.py", line 92, in <module>
    main(args)
  File "tools/train.py", line 87, in main
    trainer.run(train_dataloader, val_dataloader, evaluator)
  File "/home/zhiyuan/TSR/nanodet/nanodet/trainer/trainer.py", line 123, in run
    self.warm_up(train_loader)
  File "/home/zhiyuan/TSR/nanodet/nanodet/trainer/trainer.py", line 188, in warm_up
    for iter_id, batch in enumerate(data_loader):
  File "/home/zhiyuan/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/zhiyuan/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "/home/zhiyuan/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1024, in _get_data
    success, data = self._try_get_data()
  File "/home/zhiyuan/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/zhiyuan/anaconda3/lib/python3.7/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/home/zhiyuan/anaconda3/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

**Comment by Zhiyuan-Li-ANU** [comment]
It is a dataloading problem caused by threading.py. It can be solved by setting workers_per_gpu parameters into 0. By the way, if you training is stucked in epoch 10 with the explaination of gotit = waiter.acquire(True, timeout), you can also solve it by setting num_workers as 0 in train.py

**Comment by Zhiyuan-Li-ANU** [comment]
For more details, please check the below link: https://github.com/pytorch/pytorch/issues/1355

**Comment by LMerCy** [comment]
@Zhiyuan-Li-ANU The training speed will be much slower if workers_per_gpu  is 0 which cannot be accepted, i found many people who meet this problem seems to use their own dataset. How do you parse your annotation? Do you read the img in dataset get_item?

**Comment by Zhiyuan-Li-ANU** [comment]
@LMerCy Hello, actually there are some other ways to fix these questions. The first one is to not use CV2.imread to read the image. However, it will cause you to rewrite the whole project. The secodn way, if you want to keep use cv2, you should use cv2.setNumThreads(0) and cv2.ocl.setUseOpenCL(Flase) to close the mutitask of Opencv. I haven't try these two commands so I am not sure whether it can work.

**Comment by LMerCy** [comment]
@Zhiyuan-Li-ANU  Ok, thanks, i will have a try. Do i need to add these two commands in mmcv's loadfromfile hooks?
