### ISSUE TITLE
yaml.scanner.ScannerError: mapping values are not allowed

### ISSUE THREAD

**Issue by PCRKTY** [RangiLyu/nanodet#219]
尝试跑了一下，修改相应路径后训练时报错

python tools/train.py config/nanodet-m.ymlTraceback (most recent call last):
  File "tools/train.py", line 96, in <module>
    main(args)
  File "tools/train.py", line 42, in main
    load_config(cfg, args.config)
  File "/home/hzdjb/桌面/nanodet/nanodet/util/config.py", line 31, in load_config
    cfg.merge_from_file(args_cfg)
  File "/home/hzdjb/桌面/nanodet/nanodet/util/yacs.py", line 212, in merge_from_file
    cfg = self.load_cfg(f)
  File "/home/hzdjb/桌面/nanodet/nanodet/util/yacs.py", line 349, in load_cfg
    return cls._load_cfg_from_file(cfg_file_obj_or_str)
  File "/home/hzdjb/桌面/nanodet/nanodet/util/yacs.py", line 358, in _load_cfg_from_file
    return cls._load_cfg_from_yaml_str(file_obj.read())
  File "/home/hzdjb/桌面/nanodet/nanodet/util/yacs.py", line 370, in _load_cfg_from_yaml_str
    cfg_as_dict = yaml.safe_load(str_obj)
  File "/home/hzdjb/anaconda3/envs/nanodet/lib/python3.6/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/home/hzdjb/anaconda3/envs/nanodet/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/hzdjb/anaconda3/envs/nanodet/lib/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/hzdjb/anaconda3/envs/nanodet/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/hzdjb/anaconda3/envs/nanodet/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/hzdjb/anaconda3/envs/nanodet/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/hzdjb/anaconda3/envs/nanodet/lib/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/hzdjb/anaconda3/envs/nanodet/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/hzdjb/anaconda3/envs/nanodet/lib/python3.6/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/hzdjb/anaconda3/envs/nanodet/lib/python3.6/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/hzdjb/anaconda3/envs/nanodet/lib/python3.6/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/home/hzdjb/anaconda3/envs/nanodet/lib/python3.6/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 76, column 12:
      optimizer:
               ^

不知道哪里出了问题？感谢回复

**Comment by RangiLyu** [comment]
可能是书写不符合yaml格式
