### ISSUE TITLE
After 10 epoch error when val_intervals: 1 is list index out of range

### ISSUE THREAD

**Issue by ammm56** [RangiLyu/nanodet#223]
错误1：训练10次后验证错误，错误信息为 list index out of range，此时的results0.json文件为空。
错误1消失后，results0.json文件内容不完整，box[ 之后的文本内容没有。错误为json解析失败。
修改yml的val_intervals: 1 之后，错误为 list index out of range。

报错信息如下：

> [root][04-20 18:44:37]INFO:Val|Epoch1/100|Iter12(15)| lr:1.90e-02| loss_qfl:0.4422| loss_bbox:1.3326| loss_dfl:0.5182|
[root][04-20 18:44:37]INFO:Val|Epoch1/100|Iter12(20)| lr:1.90e-02| loss_qfl:1.4747| loss_bbox:0.6499| loss_dfl:0.5189|
Loading and preparing results...
Traceback (most recent call last):
  File "tools/train.py", line 98, in <module>
    main(args)
  File "tools/train.py", line 93, in main
    trainer.fit(task, train_dataloader, val_dataloader)
  File "D:\Python\Python37\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 499, in fit
    self.dispatch()
  File "D:\Python\Python37\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "D:\Python\Python37\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "D:\Python\Python37\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "D:\Python\Python37\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 637, in run_train
    self.train_loop.run_training_epoch()
  File "D:\Python\Python37\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 577, in run_training_epoch
    self.trainer.run_evaluation(on_epoch=True)
  File "D:\Python\Python37\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 742, in run_evaluation
    deprecated_eval_results = self.evaluation_loop.evaluation_epoch_end()
  File "D:\Python\Python37\lib\site-packages\pytorch_lightning\trainer\evaluation_loop.py", line 189, in evaluation_epoch_end
    deprecated_results = self.__run_eval_epoch_end(self.num_dataloaders)
  File "D:\Python\Python37\lib\site-packages\pytorch_lightning\trainer\evaluation_loop.py", line 227, in __run_eval_epoch_end
    eval_results = model.validation_epoch_end(eval_results)
  File "t:\nanodet\nanodet\trainer\task.py", line 112, in validation_epoch_end
    eval_results = self.evaluator.evaluate(results, self.cfg.save_dir, rank=self.local_rank)
  File "t:\nanodet\nanodet\evaluator\coco_detection.py", line 55, in evaluate
    coco_dets = self.coco_api.loadRes(json_path)
  File "D:\Python\Python37\lib\site-packages\pycocotools\coco.py", line 328, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range

**Comment by ammm56** [comment]
这是yml文件内容，标注格式是voc xml。
> #Config File example
save_dir: workspace/nanodet_test
model:
  arch:
    name: OneStageDetector
    backbone:
      name: EfficientNetLite
      model_name: efficientnet_lite0
      out_stages: [2,4,6]
      activation: ReLU6
    fpn:
      name: PAN
      in_channels: [40, 112, 320]
      out_channels: 96
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 1 #Please fill in the number of categories (not include background category)
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
class_names: ['test']   #Please fill in the category names (not include background category)
data:
  train:
    name: xml_dataset
    class_names: ['test']
    img_path: W:\nanodet\images\train  #Please fill in train image path
    ann_path: W:\nanodet\labels\train  #Please fill in train xml path
    input_size: [320,320] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.8, 1.2]
      saturation: [0.8, 1.2]
      normalize: [[127.0, 127.0, 127.0], [128.0, 128.0, 128.0]]
  val:
    name: xml_dataset
    class_names: ['test']
    img_path: W:\nanodet\images\val #Please fill in val image path
    ann_path: W:\nanodet\labels\val #Please fill in val xml path
    input_size: [320,320] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[127.0, 127.0, 127.0], [128.0, 128.0, 128.0]]
device:
  gpu_ids: [0]
  workers_per_gpu: 1
  batchsize_per_gpu: 4
schedule:
  optimizer:
    name: SGD
    lr: 0.14
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 300
    ratio: 0.1
  total_epochs: 100
  lr_schedule:
    name: MultiStepLR
    milestones: [140,170,180,185]
    gamma: 0.1
  val_intervals: 1
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
log:
  interval: 5

**Comment by ammm56** [comment]
results0.json 内容为 `[{"image_id": 1, "category_id": 1, "bbox": [`

错误信息：TypeError: Object of type Tensor is not JSON serializable
