### ISSUE TITLE
python demo_mnn.py cannot reshape array of size 100 into shape (80)

### ISSUE THREAD

**Issue by ammm56** [RangiLyu/nanodet#226]
> Traceback (most recent call last):
  File "demo_mnn/python/demo_mnn.py", line 526, in <module>
    main()
  File "demo_mnn/python/demo_mnn.py", line 512, in main
    detector.detect_folder(args.img_fold, args.result_fold)
  File "demo_mnn/python/demo_mnn.py", line 402, in detect_folder
    bbox, label, score = self.detect(img)
  File "demo_mnn/python/demo_mnn.py", line 376, in detect
    scores, raw_boxes = self.infer_image(img_input)
  File "demo_mnn/python/demo_mnn.py", line 433, in infer_image
    scores = [np.reshape(x, (-1, 80)) for x in scores]
  File "demo_mnn/python/demo_mnn.py", line 433, in <listcomp>
    scores = [np.reshape(x, (-1, 80)) for x in scores]
  File "<__array_function__ internals>", line 6, in reshape
  File "D:\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "D:\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 100 into shape (80)

**Comment by berylyellow** [comment]
@ammm56 Hi~ How did you solve it?
