### ISSUE TITLE
使用xml格式训练时报错

### ISSUE THREAD

**Issue by PCRKTY** [RangiLyu/nanodet#227]
尝试使用nanodet_custom_xml_dataset.yml训练时报错，排查后发现训练数据集VOC2007可以跑通，VOC2012会报错

```
[root][04-22 14:08:33]INFO:Using Tensorboard, logs will be saved in workspace/nanodet_m_xml_0712/logs
[root][04-22 14:08:33]INFO:Setting up data...
[root][04-22 14:08:33]INFO:loading annotations into memory...
[root][04-22 14:08:33]INFO:Found 17125 annotation files.
Traceback (most recent call last):
  File "tools/train.py", line 96, in <module>
    main(args)
  File "tools/train.py", line 54, in main
    train_dataset = build_dataset(cfg.data.train, 'train')
  File "/home/hzdjb/桌面/nanodet/nanodet/data/dataset/__init__.py", line 12, in build_dataset
    return XMLDataset(mode=mode, **dataset_cfg)
  File "/home/hzdjb/桌面/nanodet/nanodet/data/dataset/xml_dataset.py", line 44, in __init__
    super(XMLDataset, self).__init__(**kwargs)
  File "/home/hzdjb/桌面/nanodet/nanodet/data/dataset/base.py", line 52, in __init__
    self.data_info = self.get_data_info(ann_path)
  File "/home/hzdjb/桌面/nanodet/nanodet/data/dataset/xml_dataset.py", line 123, in get_data_info
    coco_dict = self.xml_to_coco(ann_path)
  File "/home/hzdjb/桌面/nanodet/nanodet/data/dataset/xml_dataset.py", line 84, in xml_to_coco
    ymin = int(_object.find('bndbox').find('ymin').text)
ValueError: invalid literal for int() with base 10: '281.70000076293945'

```
看了一下发现是VOC07和VOC12 xml标注文件命名格式不一样，VOC12命名会多一个年份前缀比如“2008_”
请问有什么方法可以批量转换吗？或者别的解决方法？感谢回复

**Comment by PCRKTY** [comment]
修改
`ymin = int(_object.find('bndbox').find('ymin').text)`
为
`ymin =int(float(_object.find('bndbox').find('ymin').text))`
