### ISSUE TITLE
Overflow when unpacking long

### ISSUE THREAD

**Issue by maylad31** [RangiLyu/nanodet#252]
Hi,
Nice work! However when i run it colab, i get this error...

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/content/drive/My Drive/nanodet/nanodet/data/collate.py", line 51, in collate_function
    return {key: collate_function([d[key] for d in batch]) for key in elem}
  File "/content/drive/My Drive/nanodet/nanodet/data/collate.py", line 51, in <dictcomp>
    return {key: collate_function([d[key] for d in batch]) for key in elem}
  File "/content/drive/My Drive/nanodet/nanodet/data/collate.py", line 51, in collate_function
    return {key: collate_function([d[key] for d in batch]) for key in elem}
  File "/content/drive/My Drive/nanodet/nanodet/data/collate.py", line 51, in <dictcomp>
    return {key: collate_function([d[key] for d in batch]) for key in elem}
  File "/content/drive/My Drive/nanodet/nanodet/data/collate.py", line 47, in collate_function
    return torch.tensor(batch)
RuntimeError: Overflow when unpacking long

**Comment by maylad31** [comment]
There was an issue in my dataset. Thanks!

**Comment by usernameoliver** [comment]
Could you please tell me what specific issue was in your dataset? I met the same runtime error. Thanks.
