### ISSUE TITLE
‘NotImplementedError’  when running export_onnx.py for  mnn_demo

### ISSUE THREAD

**Issue by cefengxu** [RangiLyu/nanodet#264]
hello  , 求解答。

把 model_zoo下的nanodet_m.ckpt ，通过 export_onnx.py 转换， 命令如下：
```
python export_onnx.py ../config/nanodet-m.yml  ../ckpt/nanodet_m.ckpt  
```
输出错误：
```
Traceback (most recent call last):
  File "/home/cefengxu/pyProjects/nanodet/tools/export_onnx.py", line 77, in <module>
    main(cfg, model_path, out_path, input_shape)
  File "/home/cefengxu/pyProjects/nanodet/tools/export_onnx.py", line 18, in main
    model = build_model(config.model)
  File "/home/cefengxu/anaconda3/lib/python3.7/site-packages/nanodet/model/arch/__init__.py", line 7, in build_model
    raise NotImplementedError
NotImplementedError

Process finished with exit code 1

```
重新查看yml，发现 model_cfg.arch.name 中，并没有包含  'GFL' 的关键字。

**Comment by RangiLyu** [comment]
model.arch.name应该是OneStageDetector，你的配置文件是怎么写的呢？

**Comment by cefengxu** [comment]
原始配置文件(nanodet-m.yml) 的model.arch.name 都是OneStageDetector。但是，基于**nanodet-m.yml** 和 **nanodet_m.ckpt**，执行 export_onnx.py 后，就会出现此 issue 前面提到的错误。

跟踪代码，执行到**nanodet/model/arch/__init__.py**，出现错误（具体源码如下）:
```
# nanodet/model/arch/__init__.py

from .gfl import GFL

def build_model(model_cfg):
    if model_cfg.arch.name == 'GFL':
        return GFL(model_cfg.arch.backbone, model_cfg.arch.fpn, model_cfg.arch.head)
    else:
        raise NotImplementedError
```
所以，我把 nanodet-m.yml 中的 model.arch.name 修改为**GFL** 从而绕过了错误

**Comment by RangiLyu** [comment]
需要更新到最新版本
