### ISSUE TITLE
Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by xiaomujiang** [RangiLyu/nanodet#291]
after install env, i  run : python tools/train.py config/nanodet_custom_xml_dataset.yml 
it have a error:
Traceback (most recent call last):
  File "tools/train.py", line 8, in <module>
    from nanodet.util import mkdir, Logger, cfg, load_config
  File "/project/train/src_repo_na/nanodet/util/__init__.py", line 10, in <module>
    from .visualization import Visualizer, overlay_bbox_cv
  File "/project/train/src_repo_na/nanodet/util/visualization.py", line 4, in <module>
    import pycocotools.mask as mask_util
  File "/mnt/sdl/anaconda3/envs/y5/lib/python3.8/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by RangiLyu** [comment]
What's your numpy version and pycocotools version? Try to downgrade numpy or upgrade pycocotools.
