### ISSUE TITLE
demo on image error

### ISSUE THREAD

**Issue by henbucuoshanghai** [RangiLyu/nanodet#316]
Finish initialize NanoDet Head.
Traceback (most recent call last):
  File "demo/demo.py", line 157, in <module>
    main()
  File "demo/demo.py", line 102, in main
    predictor = Predictor(cfg, args.model, logger, device="cuda:0")
  File "demo/demo.py", line 43, in __init__
    load_model_weight(model, ckpt, logger)
  File "/home/li/nanodet/nanodet/util/check_point.py", line 24, in load_model_weight
    state_dict = checkpoint["state_dict"]
KeyError: 'state_dict'

**Comment by henbucuoshanghai** [comment]
python demo/demo.py video --config config/nanodet-g.yml --model shufflenetv2_x1-5666bf0f80.pth --path demo_mnn/imgs/000252.jpg 
what is wrong???tks
