### ISSUE TITLE
关于训练到最后一个epoch时，会报错IndexError: list index out of range

### ISSUE THREAD

**Issue by LaoGanGit** [RangiLyu/nanodet#346]
Traceback (most recent call last):
  File "tools/train.py", line 92, in <module>
    main(args)
  File "tools/train.py", line 87, in main
    trainer.run(train_dataloader, val_dataloader, evaluator)
  File "d:\it\project\pytorch\deep-learning-for-image-processing-master\pytorch_object_detection\nanodet\nanodet\trainer\trainer.py",
line 148, in run
    eval_results = evaluator.evaluate(results, self.cfg.save_dir, epoch, self.logger, rank=self.rank)
  File "d:\it\project\pytorch\deep-learning-for-image-processing-master\pytorch_object_detection\nanodet\nanodet\evaluator\coco_detect
ion.py", line 52, in evaluate
    results_json = self.results2json(results)
  File "d:\it\project\pytorch\deep-learning-for-image-processing-master\pytorch_object_detection\nanodet\nanodet\evaluator\coco_detect
ion.py", line 40, in results2json
    category_id = self.cat_ids[label]
IndexError: list index out of range
作者您好，这是报错的代码，请教作者出现超出范围是数据集或者config参数哪里没写对吗

**Comment by RangiLyu** [comment]
一般来说是num_classes与数据集里的类别数不一致

**Comment by LaoGanGit** [comment]
> 一般来说是num_classes与数据集里的类别数不一致

谢谢作者的解答，这个问题已经解决了

**Comment by MagicCodess** [comment]
> 数据

请问是为什么呢

**Comment by sinx-cosxO-O** [comment]
请问是怎么解决的呢
