### ISSUE TITLE
pytorch_lightning.utilities.exceptions.MisconfigurationException

### ISSUE THREAD

**Issue by ChinaRush** [RangiLyu/nanodet#372]
raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: Total length of `Dataloader` across ranks is zero. Please make sure that it returns at least 1 batch.

**Comment by RangiLyu** [comment]
It seems that your dataset is loaded incorrectly.

**Comment by ChinaRush** [comment]
我用Nanodet 可以训练， 数据加载应该是对的，


`(torch) shaw@shaw:~/workspace/nanodet_plus$ python tools/train.py ./config/nanodet_custom_xml_dataset.yml 
[NanoDet][12-29 17:58:38]INFO:Setting up data...
creating index...
index created!
creating index...
index created!
[NanoDet][12-29 17:58:38]INFO:Creating model...
INFO:NanoDet:Creating model...
model size is  1.0x
init weights...
=> loading pretrained model https://download.pytorch.org/models/shufflenetv2_x1-5666bf0f80.pth
Finish initialize NanoDet-Plus Head.
/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/callbacks/progress/progress.py:21: LightningDeprecationWarning: `ProgressBar` has been deprecated in v1.5 and will be removed in v1.7. It has been renamed to `TQDMProgressBar` instead.
  rank_zero_deprecation(
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py:143: LightningDeprecationWarning: The `LightningModule.get_progress_bar_dict` method was deprecated in v1.5 and will be removed in v1.7. Please use the `ProgressBarBase.get_metrics` instead.
  rank_zero_deprecation(
/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py:284: LightningDeprecationWarning: Base `LightningModule.on_train_batch_end` hook signature has changed in v1.5. The `dataloader_idx` argument will be removed in v1.7.
  rank_zero_deprecation(
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type        | Params
------------------------------------------
0 | model     | NanoDetPlus | 4.2 M 
1 | avg_model | NanoDetPlus | 4.2 M 
------------------------------------------
8.3 M     Trainable params
0         Non-trainable params
8.3 M     Total params
33.326    Total estimated model params size (MB)
[NanoDet][12-29 17:58:40]INFO:Weight Averaging is enabled
INFO:NanoDet:Weight Averaging is enabled
Traceback (most recent call last):
  File "tools/train.py", line 136, in <module>
    main(args)
  File "tools/train.py", line 131, in main
    trainer.fit(task, train_dataloader, val_dataloader)
  File "/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 738, in fit
    self._call_and_handle_interrupt(
  File "/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 683, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 773, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
  File "/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1275, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1285, in run_stage
    return self._run_train()
  File "/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1315, in _run_train
    self.fit_loop.run()
  File "/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 140, in run
    self.on_run_start(*args, **kwargs)
  File "/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 197, in on_run_start
    self.trainer.reset_train_val_dataloaders(self.trainer.lightning_module)
  File "/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 571, in reset_train_val_dataloaders
    self.reset_val_dataloader(model=model)
  File "/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 528, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(
  File "/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 485, in _reset_eval_dataloader
    if has_len_all_ranks(dataloader, self.training_type_plugin, module)
  File "/home/shaw/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py", line 118, in has_len_all_ranks
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: Total length of `Dataloader` across ranks is zero. Please make sure that it returns at least 1 batch.`

**Comment by RangiLyu** [comment]
验证集没加载上

**Comment by ChinaRush** [comment]
果然， 验证集 valid 拼错了
