### ISSUE TITLE
Issue when converting to ONNX

### ISSUE THREAD

**Issue by dual19** [RangiLyu/nanodet#386]
I am getting an error when trying to convert my custom model_best.ckpt to ONNX. Do you have an suggestions to resolve this issue?

> Traceback (most recent call last):
  File "/home/drone_vision/Repos/AutoDrone_ObjectTracking/nanodet/./tools/export_onnx.py", line 104, in <module>
    main(cfg, model_path, out_path, input_shape)
  File "/home/drone_vision/Repos/AutoDrone_ObjectTracking/nanodet/./tools/export_onnx.py", line 50, in main
    torch.onnx.export(
  File "/home/drone_vision/.conda/envs/SampleSolution/lib/python3.9/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/drone_vision/.conda/envs/SampleSolution/lib/python3.9/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/drone_vision/.conda/envs/SampleSolution/lib/python3.9/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/drone_vision/.conda/envs/SampleSolution/lib/python3.9/site-packages/torch/onnx/utils.py", line 493, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/drone_vision/.conda/envs/SampleSolution/lib/python3.9/site-packages/torch/onnx/utils.py", line 437, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/drone_vision/.conda/envs/SampleSolution/lib/python3.9/site-packages/torch/onnx/utils.py", line 388, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/drone_vision/.conda/envs/SampleSolution/lib/python3.9/site-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/drone_vision/.conda/envs/SampleSolution/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/drone_vision/.conda/envs/SampleSolution/lib/python3.9/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/drone_vision/.conda/envs/SampleSolution/lib/python3.9/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/drone_vision/.conda/envs/SampleSolution/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/drone_vision/.conda/envs/SampleSolution/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/drone_vision/Repos/AutoDrone_ObjectTracking/nanodet/nanodet/model/arch/one_stage_detector.py", line 43, in forward
    x = self.fpn(x)
  File "/home/drone_vision/.conda/envs/SampleSolution/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/drone_vision/.conda/envs/SampleSolution/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/drone_vision/Repos/AutoDrone_ObjectTracking/nanodet/nanodet/model/fpn/ghost_pan.py", line 223, in forward
    torch.cat([upsample_feat, feat_low], 1)
**RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 24 but got size 23 for tensor number 1 in the list**

**Comment by dual19** [comment]
I have discovered that this issue is caused by my training input resolution, which was 640x360. Is it possible to use a custom resolution and convert to ONNX?

**Comment by YUANRUICHENG** [comment]
hello，I have the same problem as you. Have you solved it now?

**Comment by mmkolbe** [comment]
> Image size must be a multiple of 32. 512x288 will convert.

Worked. Saved the day. Thanks man.
