### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by Elias9898** [RangiLyu/nanodet#440]
hi!  我在用voc数据集训练模型时得到以下报错，
当前路径是：
img_path: \\D:\\dataset\\train\\images
    ann_path: \\D:\\dataset\\train\\annotations

[NanoDet][05-29 05:04:59]INFO:Setting up data...
creating index...
index created!
creating index...
index created!
Traceback (most recent call last):
  File "tools/train.py", line 136, in <module>
    main(args)
  File "tools/train.py", line 75, in main
    train_dataloader = torch.utils.data.DataLoader(
  File "C:\Users\33184\anaconda3\envs\nanodet\lib\site-packages\torch\utils\data\dataloader.py", line 277, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "C:\Users\33184\anaconda3\envs\nanodet\lib\site-packages\torch\utils\data\sampler.py", line 97, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

感谢

**Comment by Juanting-Xu** [comment]
同样遇到这个问题，请问解决了吗

**Comment by Elias9898** [comment]
> 

还没有

**Comment by ParthibanMarimuthu** [comment]
You set the wrong path and the model cannot find the training data to start training (
您设置了错误的路径，模型找不到训练数据开始训练)

**Comment by bjflwr123** [comment]
shuffle=False can solve this problem

**Comment by Trumpetertimes** [comment]
请问解决了吗，我卡到了这一步。

**Comment by zhuleia** [comment]
请问解决了吗？
