### ISSUE TITLE
KeyError:'images' KeyError: Caught KeyError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by RMsu233** [RangiLyu/nanodet#508]
[NanoDet][04-05 20:27:52]INFO:Setting up data...
creating index...
index created!
creating index...
index created!
[NanoDet][04-05 20:27:53]INFO:Creating model...
INFO:NanoDet:Creating model...
model size is  1.0x
init weights...
=> loading pretrained model https://download.pytorch.org/models/shufflenetv2_x1-5666bf0f80.pth
Finish initialize NanoDet-Plus Head.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3060 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type        | Params
------------------------------------------
0 | model     | NanoDetPlus | 4.2 M 
1 | avg_model | NanoDetPlus | 4.2 M 
------------------------------------------
8.5 M     Trainable params
0         Non-trainable params
8.5 M     Total params
33.902    Total estimated model params size (MB)
[NanoDet][04-05 20:27:54]INFO:Weight Averaging is enabled
INFO:NanoDet:Weight Averaging is enabled
Epoch 0:   0%|                                                                                                                                                                                        | 0/525 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tools/train.py", line 155, in <module>
    main(args)
  File "tools/train.py", line 150, in main
    trainer.fit(task, train_dataloader, val_dataloader, ckpt_path=model_resume_path)
  File "/home/rmsu233/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/rmsu233/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/rmsu233/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/rmsu233/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/home/rmsu233/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/home/rmsu233/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1205, in _run_train
    self.fit_loop.run()
  File "/home/rmsu233/.local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/rmsu233/.local/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/rmsu233/.local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/rmsu233/.local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 187, in advance
    batch = next(data_fetcher)
  File "/home/rmsu233/.local/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "/home/rmsu233/.local/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 265, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/home/rmsu233/.local/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 280, in _fetch_next_batch
    batch = next(iterator)
  File "/home/rmsu233/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 569, in __next__
    return self.request_next_batch(self.loader_iters)
  File "/home/rmsu233/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 581, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next)
  File "/home/rmsu233/.local/lib/python3.8/site-packages/lightning_utilities/core/apply_func.py", line 51, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/home/rmsu233/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/rmsu233/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/rmsu233/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/rmsu233/.local/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/rmsu233/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/rmsu233/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rmsu233/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rmsu233/nanodet/nanodet/data/dataset/base.py", line 84, in __getitem__
    data = self.get_train_data(idx)
  File "/home/rmsu233/nanodet/nanodet/data/dataset/coco.py", line 147, in get_train_data
    meta = self.pipeline(self, meta, input_size)
  File "/home/rmsu233/nanodet/nanodet/data/transform/pipeline.py", line 57, in __call__
    meta = self.shape_transform(meta, dst_shape=dst_shape)
  File "/home/rmsu233/nanodet/nanodet/data/transform/warp.py", line 308, in __call__
    raw_img = meta_data["images"]
KeyError: 'images'

Epoch 0:   0%|          | 0/525 [00:01<?, ?it/s]

**Comment by RMsu233** [comment]
我修改了config/nanodet_custom_xml_dataset.yml文件下的class_name和num_class
以及train&&val: /img_path /ann_path
出现了上述报错
