### ISSUE TITLE
My CUDA Version is 10.2 with the "RuntimeError: The NVIDIA driver on your system is too old"

### ISSUE THREAD

**Issue by cuchanxiao** [RangiLyu/nanodet#94]
$ python demo/demo.py video --config config/nanodet-m.yml --model nanodet_m.pth --path video480p.mov 

model size is  1.0x
init weights...
=> loading pretrained model https://download.pytorch.org/models/shufflenetv2_x1-5666bf0f80.pth
Finish initialize Lite GFL Head.
Traceback (most recent call last):
  File "demo/demo.py", line 106, in <module>
    main()
  File "demo/demo.py", line 80, in main
    predictor = Predictor(cfg, args.model, logger, device='cuda:0')
  File "demo/demo.py", line 33, in __init__
    self.model = model.to(device).eval()
  File "/home/cuc/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 612, in to
    return self._apply(convert)
  File "/home/cuc/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/cuc/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/cuc/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/cuc/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/cuc/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/home/cuc/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 10020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

$ nvidia-smi
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |

how can i fix it, please?

**Comment by duyanfang123** [comment]
https://pytorch.org/get-started/previous-versions/

**Comment by duyanfang123** [comment]
https://pytorch.org/get-started/previous-versions/
This page really help me to resolve this problem

**Comment by cuchanxiao** [comment]
> https://pytorch.org/get-started/previous-versions/
> This page really help me to resolve this problem

Thanks! It does help me out!

**Comment by cyjouc** [comment]
my version:
conda list | grep cuda
cudatoolkit 10.2.89 hfd86e86_1
cudnn 7.6.5 cuda10.2_0
pytorch 1.7.1

**Comment by cyjouc** [comment]
How do you the sovle?
I run the code :conda install pytorch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0 cudatoolkit=10.2 -c pytorch
the error can not be solved
